global_costmap:
  global_frame: map    #地图坐标系
  robot_base_frame: base_link    #机器人坐标系

  
  update_frequency: 1.0  #代价地图更新频率 
  #static_map: true  #是否使用一个地图或者地图服务器来初始化全局代价地图，如果不使用静态地图，该参数为false    原始被注释掉的
  
  update_frequency: 1.0 #代价地图的发布频率
  rolling_window: false
  resolution: 0.05
  
  #从costmap_common_params.yaml中copy过来新加的
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10) 代价比例系数，越大则代价值越小   原始为5
  inflation_radius:     0.4  # max. distance from an obstacle at which costs are incurred for planning paths.  膨胀半径，扩展在碰撞区以外的代价区域，使得机器人规划路径避开障碍物  原始为0.25
  #结束

  transform_tolerance: 0.5  #等待坐标变换发布信息的超时时间    原始为1
  ##map_type: costmap
  ##map_type: voxel
  ##inflation_radius: 0.1
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

