local_costmap:
  global_frame: odom     #在局部代价地图中的全局坐标系
  robot_base_frame: base_link    #机器人本体的基坐标系
  update_frequency: 3.0   #局部代价地图的更新频率;
  publish_frequency: 3.0  #局部代价地图的发布频率;
  #static_map: false      #局部代价地图一般不设置为静态地图，因为需要检测是否在机器人附近有新增的动态障碍物;
  
  cost_scaling_factor:  5.0  # 代价比例系数，越大则代价值越小   原始为5
  inflation_radius:     0.3  # 膨胀半径，扩展在碰撞区以外的代价区域，使得机器人规划路径避开障碍物  原始为0.25

  
  
  rolling_window: true    #使用滚动窗口，始终保持机器人在当前局部地图的中心位置;
  width: 2.5              #滚动窗口的宽度，单位是米;
  height: 2.5             #滚动窗口的高度，单位是米;
  resolution: 0.05        #地图的分辨率，该分辨率可以从加载的地图相对应的配置文件中获取到;
  plugins: 
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"} 
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
#在局部代价地图中，不需要静态地图层，因为我们使用滚动窗口来不断的扫描障碍物，
#所以就需要融合两层地图（inflation_layer和obstacle_layer）即可，融合后的地图用于进行局部路径规划;