# 调大了inflation dist、costmap_obstacles_behind_robot_dist，调小了min_obstacle_dist

TebLocalPlannerROS:

  odom_topic: odom
  map_frame: odom
    
 # Trajectory
  
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  max_samples: 500
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: True
  max_global_plan_lookahead_dist: 10.0  #  used 3.0
  global_plan_viapoint_sep: -1
  global_plan_prune_distance: 1
  exact_arc_length: False
  feasibility_check_no_poses: 2
  publish_feedback: False
      
 # Robot
  #allow_init_with_backwards_motion: false
  max_vel_x: 0.75
  max_vel_x_backwards: 0.2 #最大倒车速度。将此速度设置为0或者负数将导致错误。禁止倒车应在penalty部分将前向行驶的权重设置得极高。
  acc_lim_x: 100
  max_vel_y: 0.0

  max_vel_theta: 1
  acc_lim_theta: 100

  # ## Costmap converter plugin   
  # costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  # #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  # #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  # #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  # #costmap_converter_plugin: "" # deactivate plugin
  # costmap_converter_spin_thread: True
  # costmap_converter_rate: 5
 
 
  ## Configure plugins (namespace move_base/TebLocalPlannerROS/PLUGINNAME)
  ## The parameters must be added for each plugin separately
  # costmap_converter/CostmapToLinesDBSRANSAC:
  #   cluster_max_distance: 0.4
  #   cluster_min_pts: 2
  #   ransac_inlier_distance: 0.15
  #   ransac_min_inliers: 10
  #   ransac_no_iterations: 2000
  #   ransac_remainig_outliers: 3
  #   ransac_convert_outlier_pts: True
  #   ransac_filter_remaining_outlier_pts: False
  #   convex_hull_min_pt_separation: 0.1
  
  # ********************** Carlike robot parameters ********************
  min_turning_radius: 0.76        # Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
  wheelbase: 0.3                 # Wheelbase of our robot  前后轮距离。
  cmd_angle_instead_rotvel: True # stage simulator takes the angle instead of the rotvel as input (twist message)
  # ********************************************************************

  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "line"
    #radius: 0.2 # for type "circular"
    line_start: [-0.2, 0.0] # for type "line"
    line_end: [0.2, 0.0] # for type "line"
    #front_offset: 0.2 # for type "two_circles"
    #front_radius: 0.2 # for type "two_circles"
    #rear_offset: 0.2 # for type "two_circles"
    #rear_radius: 0.2 # for type "two_circles"
    #vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

 # GoalTolerance
      
  xy_goal_tolerance: 0.1  #used 0.4
  yaw_goal_tolerance: 0.1   #used  0.2
  free_goal_vel: False
  complete_global_plan: True
    
 # Obstacles
  inflation_dist: 0.8    # used 0.3 #障碍物周围的缓冲区，进缓冲区会导致规划器减速，不过这个值得比min_obstacle_dist大才有效
  min_obstacle_dist: 0.22     #  used 0.24  #是与障碍物的最小期望距离，米为单位。
  include_costmap_obstacles: True  #这个必须设置成true才能规避实时探测到的，建图时不存在的障碍物
  costmap_obstacles_behind_robot_dist: 1.0  #used  1.0
  obstacle_poses_affected: 20
  dynamic_obstacle_inflation_dist: 1.0
  include_dynamic_obstacles: True 

  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 8

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 4
  weight_max_vel_x: 0.89
  weight_max_vel_theta: 0.98
  weight_acc_lim_x: 0.69
  weight_acc_lim_theta: 0.83
  weight_kinematics_nh: 1000    #迫使机器人只选择前进的方向，也就是权重越大，倒车惩罚越大。(0~1000)
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1   #机器人最小转向半径的权重，越大则越容易达到最小转向半径的情况。 (0~1000)
  
  weight_optimaltime: 5 # must be > 0
  #这个参数是最优时间权重，如果大了，那么车会在直道上快速加速，并且路径规划的也会切内道，这是DWA算法只能靠膨胀缩小来实现的。
  #这个参数越小，整个过程的车速会越稳定。我试过了0.5和2.5这两个值，差距还是蛮明显的，各位可以自己试试看体会一下，范围同样是0~1000。
  
  weight_shortest_path: 0
  weight_obstacle: 100
  weight_inflation: 0.2
  weight_dynamic_obstacle: 10 # not in use yet
  weight_dynamic_obstacle_inflation: 0.2
  weight_viapoint: 1
  weight_adapt_factor: 2

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.95
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
  delete_detours_backwards: True
  max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: False
  visualize_with_time_as_z_axis_scale: False


#  Recovery

  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10